use reqwest::Client;
use serde::{Deserialize, Serialize};

const TELEGRAM_API_BASE: &str = "https://api.telegram.org/bot";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TelegramConfig {
    pub bot_token: String,
    pub chat_id: String,
}

pub async fn send_report(config: &TelegramConfig, report: &str) -> Result<(), String> {
    log::info!("[AUTO] Sending to Telegram...");

    let client = Client::new();
    let url = format!("{}{}/sendMessage", TELEGRAM_API_BASE, config.bot_token);

    let payload = serde_json::json!({
        "chat_id": config.chat_id,
        "text": report,
        "parse_mode": "HTML",
        "disable_web_page_preview": true,
    });

    let response = client
        .post(&url)
        .json(&payload)
        .send()
        .await
        .map_err(|e| {
            log::error!("[AUTO] Telegram failed: {}", e);
            format!("Telegram send error: {}", e)
        })?;

    if response.status().is_success() {
        log::info!("[AUTO] Telegram report sent!");
        Ok(())
    } else {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        Err(format!("Telegram API error ({}) {}", status, body))
    }
}

pub fn format_report(
    steam_id: &str,
    persona_name: &str,
    browser_hits: usize,
    memory_anomalies: usize,
    folder_threats: usize,
    prefetch_hits: usize,
    verdict: &str,
) -> String {
    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    format!(
        r#"<b>CS2Checker Report</b>

<b>Player:</b> {} ({})
<b>Date:</b> {}

<b>Results:</b>
 Browser History Hits: {}
 Memory Anomalies: {}
 Folder Threats: {}
 Prefetch Hits: {}

<b>Verdict:</b> {}

<i>Generated by CS2Checker v2.0</i>
<a href="https://cs2checker.ru">cs2checker.ru</a> | <a href="https://discord.gg/85YQR8sKFb">Discord</a>"#,
        persona_name, steam_id,
        timestamp,
        browser_hits, memory_anomalies, folder_threats, prefetch_hits,
        verdict.to_uppercase(),
    )
}

